Repository elastic/ecs-logging-java, pull requests merged in 2023-02, with the labels that each got.

#199 action: update specs
  .ci/update-specs.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/update-specs.yml
Labels: automation, agent-java, Team:Automation

#202 [updatecli] synchronize ecs-logging spec
  ecs-logging-core/src/test/resources/spec/spec.json
Labels: dependencies, agent-java

#197 ci: release automation
  .buildkite/hooks/post-command
  .buildkite/hooks/pre-command
  .buildkite/release.yml
  .buildkite/snapshot.yml
  .ci/release.sh
  .ci/snapshot.sh
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
  CONTRIBUTING.md
  README.md
Labels: agent-java

#204 automation: fix release/snapshot env context
  .buildkite/hooks/pre-command
Labels: automation, agent-java, Team:Automation

#205 release: remove local repository pointing to Jenkins and tweak errors propagation in the buildkite pipelines
  .buildkite/release.yml
  .buildkite/snapshot.yml
  .ci/release.sh
  .ci/settings.xml
  .ci/snapshot.sh
Labels: automation, agent-java, Team:Automation

#207 buildkite: fix slack notification
  .buildkite/snapshot.yml
Labels: agent-java

#208 buildkite: update references to the new env variables that are masked
  .buildkite/hooks/pre-command
  .ci/release.sh
  .ci/settings.xml
  .ci/snapshot.sh
Labels: agent-java

#209 buildkite: print maven/java context
  .buildkite/hooks/pre-command
  .ci/release.sh
  .ci/snapshot.sh
Labels: agent-java

#210 maven: upgrade target to 7
  .buildkite/hooks/pre-command
  .github/workflows/test.yml
  pom.xml
Labels: agent-java
